# Generated by Django 4.2.7 on 2023-11-22 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
